# Cars API Data

In [9]:
import requests
import json

### For one car model:

In [4]:
model = 'camry'

api_url = 'https://api.api-ninjas.com/v1/cars?model={}'.format(model)
response = requests.get(api_url, headers={'X-Api-Key': 'rtsVUhXvel9N968aGEoMeg==zciz73lsmuFNEOQM'})
if response.status_code == requests.codes.ok:
    print(response.text)
else:
    print("Error:", response.status_code, response.text)

[{"city_mpg": 18, "class": "midsize car", "combination_mpg": 21, "cylinders": 4, "displacement": 2.2, "drive": "fwd", "fuel_type": "gas", "highway_mpg": 26, "make": "toyota", "model": "camry", "transmission": "a", "year": 1993}, {"city_mpg": 19, "class": "midsize car", "combination_mpg": 22, "cylinders": 4, "displacement": 2.2, "drive": "fwd", "fuel_type": "gas", "highway_mpg": 27, "make": "toyota", "model": "camry", "transmission": "m", "year": 1993}, {"city_mpg": 16, "class": "midsize car", "combination_mpg": 19, "cylinders": 6, "displacement": 3.0, "drive": "fwd", "fuel_type": "gas", "highway_mpg": 22, "make": "toyota", "model": "camry", "transmission": "a", "year": 1993}, {"city_mpg": 16, "class": "midsize car", "combination_mpg": 18, "cylinders": 6, "displacement": 3.0, "drive": "fwd", "fuel_type": "gas", "highway_mpg": 22, "make": "toyota", "model": "camry", "transmission": "m", "year": 1993}, {"city_mpg": 18, "class": "midsize-large station wagon", "combination_mpg": 21, "cylinders": 4, "displacement": 2.2, "drive": "fwd", "fuel_type": "gas", "highway_mpg": 26, "make": "toyota", "model": "camry wagon", "transmission": "a", "year": 1993}]

### Multiple car models:

In [11]:
# Lists of car models for each manufacturer
toyota_models = ['Camry', 'Corolla', 'RAV4']
tesla_models = ['Model S', 'Model 3', 'Model X']
stla_models = ['Ram 1500', 'Jeep Wrangler', 'Fiat 500'] 
gm_models = ['Chevrolet Silverado', 'GMC Sierra', 'Cadillac Escalade']
nissan_models = ['Altima', 'Rogue', 'Leaf']
mercedes_models = ['C-Class', 'E-Class', 'S-Class']
bmw_models = ['3 Series', 'X5', 'i3']
porsche_models = ['911', 'Cayenne', 'Taycan']

# Combine all lists into one
all_models = toyota_models + tesla_models + stla_models + gm_models + nissan_models + mercedes_models + bmw_models + porsche_models

# Dictionary to store data for all models
all_data = {}

# Loop through each model and make the API call
for model in all_models:
    api_url = f'https://api.api-ninjas.com/v1/cars?model={model}'
    response = requests.get(api_url, headers={'X-Api-Key': 'rtsVUhXvel9N968aGEoMeg==zciz73lsmuFNEOQM'})

    if response.status_code == requests.codes.ok:
        # Add the response data to the dictionary
        all_data[model] = response.json()
    else:
        print(f"Error for {model}: {response.status_code} {response.text}")

# Convert the dictionary to a JSON string
json_data = json.dumps(all_data, indent=4)

# Write the JSON data to a file
with open('cars.json', 'w') as file:
    file.write(json_data)

print("JSON data saved to car_models_data.json")

JSON data saved to car_models_data.json

## Read Data from JSON File and Save as a Dataframe

In [13]:
import pandas as pd
import json

# Read the JSON file
file_path = 'cars.json'
with open(file_path, 'r') as file:
    data = json.load(file)

# Convert the JSON data to a pandas DataFrame
df_list = []
for model, records in data.items():
    for record in records:
        # Add the model name to each record
        record['model'] = model
        df_list.append(record)

# Create DataFrame from the list of dictionaries
cars_df = pd.DataFrame(df_list)

cars_df

,city_mpg,class,combination_mpg,cylinders,displacement,drive,fuel_type,highway_mpg,make,model,transmission,year
0,18,midsize car,21,4.0,2.2,fwd,gas,26,toyota,Camry,a,1993
1,19,midsize car,22,4.0,2.2,fwd,gas,27,toyota,Camry,m,1993
2,16,midsize car,19,6.0,3.0,fwd,gas,22,toyota,Camry,a,1993
3,16,midsize car,18,6.0,3.0,fwd,gas,22,toyota,Camry,m,1993
4,18,midsize-large station wagon,21,4.0,2.2,fwd,gas,26,toyota,Camry,a,1993
...,...,...,...,...,...,...,...,...,...,...,...,...
75,68,large car,69,NaN,NaN,awd,electricity,71,porsche,Taycan,a,2020
76,67,large car,68,NaN,NaN,awd,electricity,68,porsche,Taycan,a,2020
77,68,large car,69,NaN,NaN,awd,electricity,71,porsche,Taycan,a,2020
78,79,large car,79,NaN,NaN,awd,electricity,80,porsche,Taycan,a,2021
79,75,large car,77,NaN,NaN,awd,electricity,81,porsche,Taycan,a,2021

### Save Output

In [15]:
cars_df.to_csv('cars-data.csv')